GET http://localhost:5000/api/token/authorize

###
GET http://localhost/api/token/authorize

###
GET http://localhost/api/token/authorize

###
GET http://localhost/s1/wf
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InpZMk4yQ3YwMUVEQ0hTaEtfVHJsOWciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1Nzk2ODkzNjcsImV4cCI6MTU3OTY5Mjk2NywiaXNzIjoiaHR0cDovL2lkZW50aXR5LXNlcnZpY2UiLCJhdWQiOiJhcGkxIiwiY2xpZW50X2lkIjoiY2xpZW50Iiwic2NvcGUiOlsiYXBpMSJdfQ.wP4R8T-A_9XhGkGQG2826ZQj1uBI2NN8devyt8ZP0vLL8m9wxZ7-0it-RWf5gEWv4leR0SaSqGIi1p3Ta8wzTTA8w4aiw13MJ_0ONV2dH1CKZ9BV5TsmBrpQnGe2ob9IvXEIAGPFc5ZBxGOA_sfdabZYI-v2YNzi8cWI1pYgoDNUNVxU0Pm-xwK2kqXxc2GDjwg7GKayhakDaaNtns3B3Xtm5cZ9eDPPzWjNbNAY_SebBO5IZfYvQSbFQSLeBTwdD1CaUdPnPVjfvqX5Pf-9z2-3YBlIyZx_aEXGE-v6rqmoYAti5fEth3yzrlyNgP-9nZnBgBH9aZKleh_CZHOrCg
