GET http://localhost:5000/api/token/authorize

###
GET http://localhost/api/token/authorize

###
GET http://localhost/api/token/authorize

###
GET http://localhost/s1/wf
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjV0eGxfdkFJbmRvblRfWENwaUtUZkEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2MDEyOTE0NDUsImV4cCI6MTYwMTI5NTA0NSwiaXNzIjoiaHR0cDovL2lkZW50aXR5LXNlcnZpY2UiLCJhdWQiOiJhcGkxIiwiY2xpZW50X2lkIjoiY2xpZW50Iiwic2NvcGUiOlsiYXBpMSJdfQ.GyKdzULa76KnPz9kAHr_mdW7XBcQRd3aTh9CMv91wRz9CkU4_M5tSdY5aMUM4fpCmj0b2liCq_15V1tepeovP3N40aZ0MuVLlk5Mo2fF7JTXYcmvVsBplk-NVyDGhnesTvTcWT54O_PayXaZ8TNZmg4OGw9tI_o0TIQMjVJifUxaLnBlMhu8ZGTPRiOcnbcUB6TMcDp-qkX_KChFttcHeyloz466D9xJL-YiZiE4a9rnVESL7AH9-VAJNLN69ZzvnNX3pVPj9OusrrcAB6AWcUKcOKXfQzV0DOfxLAeYbjeo3x1mX5f3Sx63VuWa7IcuB6imDzohiERKlkihs2j3-Q
